### ISSUE TITLE
Unable to negotiate with …: no matching host key type found. They offer: ssh-rsa

### ISSUE THREAD

**Issue by heinrich5991** [hackclub/jobs#16] opened 2022-01-13 21:28 UTC
$ ssh jobs.hackclub.com
    Unable to negotiate with 96.126.108.99 port 22: no matching host key type found. Their offer: ssh-rsa
    $ ssh -V
    OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
    $ cat /etc/os-release | head -n1
    NAME="Arch Linux"

**Comment by KarolisL** [comment] 2022-01-13 22:30
As a workaround you could use `ssh jobs.hackclub.com -oHostKeyAlgorithms=ssh-rsa`.

Inspired by https://askubuntu.com/questions/836048/ssh-returns-no-matching-host-key-type-found-their-offer-ssh-dss

@kognise @zachlatta If the host key algo is used for some sort of gatekeeping, I'd be glad to remove the comment.

**Comment by WhyNotHugo** [comment] 2022-01-13 22:32
Any particular reason to **only** support a key type that ssh does not support out-of-the-box?

**Comment by kognise** [comment] 2022-01-14 18:52
Should be fixed since c71850bd70c4e7e11f0dcf0cd5843d9d854b54f1 (sorry for multiple commits, accidentally screwed up prod 😅)

@WhyNotHugo `ssh-rsa` was formerly supported out-of-the-box, but new OpenSSH versions removed it. Myself and most people who tested it are still running on old OpenSSH so we didn't see the issue.

Fix added `ssh-ed25519` as a supported key format, right now it's hardcoded but there could be a better way.

Gonna close this issue, if anyone can still reproduce the issue I'll give another look.

**Closed by kognise** 2022-01-14 18:52 UTC

**Comment by heinrich5991** [comment] 2022-01-14 20:22
Thanks, works for me now.
